services:
  db:
    image: postgres:16
    container_name: smarttask_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: smarttask
      POSTGRES_PASSWORD: smarttask123
      POSTGRES_DB: smarttask
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
